// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package eth

import (
	"encoding/json"
	"math/big"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/hexutil"
	"github.com/ethereum/go-ethereum/core/types"
)

var _ = (*rpcReceiptMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (r RPCReceipt) MarshalJSON() ([]byte, error) {
	type RPCReceipt struct {
		TransactionHash   common.Hash     `json:"transactionHash"`
		TransactionIndex  hexutil.Uint64  `json:"transactionIndex"`
		BlockHash         common.Hash     `json:"blockHash"`
		BlockNumber       *hexutil.Big    `json:"blockNumber"`
		From              common.Address  `json:"from"`
		To                *common.Address `json:"to"`
		CumulativeGasUsed hexutil.Uint64  `json:"cumulativeGasUsed"`
		GasUsed           hexutil.Uint64  `json:"gasUsed"`
		ContractAddress   *common.Address `json:"contractAddress"`
		Logs              []*types.Log    `json:"logs"`
		LogsBloom         types.Bloom     `json:"logsBloom"`
		Type              hexutil.Uint64  `json:"type"`
		Status            hexutil.Uint64  `json:"status"`
	}
	var enc RPCReceipt
	enc.TransactionHash = r.TransactionHash
	enc.TransactionIndex = hexutil.Uint64(r.TransactionIndex)
	enc.BlockHash = r.BlockHash
	enc.BlockNumber = (*hexutil.Big)(r.BlockNumber)
	enc.From = r.From
	enc.To = r.To
	enc.CumulativeGasUsed = hexutil.Uint64(r.CumulativeGasUsed)
	enc.GasUsed = hexutil.Uint64(r.GasUsed)
	enc.ContractAddress = r.ContractAddress
	enc.Logs = r.Logs
	enc.LogsBloom = r.LogsBloom
	enc.Type = hexutil.Uint64(r.Type)
	enc.Status = hexutil.Uint64(r.Status)
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (r *RPCReceipt) UnmarshalJSON(input []byte) error {
	type RPCReceipt struct {
		TransactionHash   *common.Hash    `json:"transactionHash"`
		TransactionIndex  *hexutil.Uint64 `json:"transactionIndex"`
		BlockHash         *common.Hash    `json:"blockHash"`
		BlockNumber       *hexutil.Big    `json:"blockNumber"`
		From              *common.Address `json:"from"`
		To                *common.Address `json:"to"`
		CumulativeGasUsed *hexutil.Uint64 `json:"cumulativeGasUsed"`
		GasUsed           *hexutil.Uint64 `json:"gasUsed"`
		ContractAddress   *common.Address `json:"contractAddress"`
		Logs              []*types.Log    `json:"logs"`
		LogsBloom         *types.Bloom    `json:"logsBloom"`
		Type              *hexutil.Uint64 `json:"type"`
		Status            *hexutil.Uint64 `json:"status"`
	}
	var dec RPCReceipt
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.TransactionHash != nil {
		r.TransactionHash = *dec.TransactionHash
	}
	if dec.TransactionIndex != nil {
		r.TransactionIndex = uint64(*dec.TransactionIndex)
	}
	if dec.BlockHash != nil {
		r.BlockHash = *dec.BlockHash
	}
	if dec.BlockNumber != nil {
		r.BlockNumber = (*big.Int)(dec.BlockNumber)
	}
	if dec.From != nil {
		r.From = *dec.From
	}
	if dec.To != nil {
		r.To = dec.To
	}
	if dec.CumulativeGasUsed != nil {
		r.CumulativeGasUsed = uint64(*dec.CumulativeGasUsed)
	}
	if dec.GasUsed != nil {
		r.GasUsed = uint64(*dec.GasUsed)
	}
	if dec.ContractAddress != nil {
		r.ContractAddress = dec.ContractAddress
	}
	if dec.Logs != nil {
		r.Logs = dec.Logs
	}
	if dec.LogsBloom != nil {
		r.LogsBloom = *dec.LogsBloom
	}
	if dec.Type != nil {
		r.Type = uint64(*dec.Type)
	}
	if dec.Status != nil {
		r.Status = uint64(*dec.Status)
	}
	return nil
}
